### PR TITLE
implemented case tolerant flag decoding for CPSID and CPSIE instructions

### PR DESCRIPTION
**Pull request by fdx1601**
Since everything else is case tolerant there is no reason the flags shouldn't be.

### CODE REVIEW

**Comment by fdx1601** [comment]
not so familiar with git ... why my separate second commit/push is showing up here? 

I supposed each pull request is linked to a specific commit.

**Comment by mikeakohn** [comment]
The case sensitivity is a good catch, but you also have changes to tokens.c that if I merge it it's going to break the fixes I was putting in for dealing with escape characters.

**Comment by fdx1601** [comment]
Yeah ... I opened the pull request after the first commit, because I didn't want the other commit to enter.

I thought GIT would manage pull requests by commit ... but obviously that isn't the case.

I fear one has to create a branch to avoid this.

**Comment by fdx1601** [comment]
not suitable because unwanted commit entered this scope

**Comment by mikeakohn** [comment]
I thin I can cherry-pick the single commit from this.. I will try after I check in my change :).

**Comment by mikeakohn** [comment]
Got it!  If you do a git pull, you should have the 1 commit here in there with your name on it still.  Thanks!

**Pull request closed without merging**
