### PR TITLE
Fix mask + opcodes for djnz and outl (8048)

### PR DESCRIPTION
**Pull request by erkkah**
This fixes faulty masks and opcodes for `djnz` and `outl`.

Also - it moves the `outl p0, a` variant to a new flag (`FLAG_8021`), since that combination only exists on 8021/8022 and clashes with two flag-specific instructions on 8041 and 8048.

Should I remove that combo instead?
FYI - I'm working on support for the NS405 variant and found these bugs. In that branch, I'm changing flag logic to a bit mask instead of an enum because of overlapping functionality between the three variants.

### CODE REVIEW

**Comment by erkkah** [comment]
Obviously, the tests will not pass until either the test for `outl p0, a` is fixed (moved to 8021 - specific tests) or removed.
Or - if the flag is removed, which again reveals the original bug.

**Comment by mikeakohn** [comment]
Nice find! About the 8021.. is that actually useful for anything? Adding the extra seems more like it'd just weigh down the other assemblers. I'm actually not sure why I even did 8041.

**Comment by erkkah** [comment]
I just didn't want to remove the 8021 - specific opcode, since I guess it was implemented for a reason :)
But - since none of the other 8021 - specifics are implemented, it might be better to just remove it.

If so, I can fix the tests to cover the new `outl` flavour.

**Comment by mikeakohn** [comment]
I think I'm confused now (it's been a really long time since I did the 8048.. and I never used it before actually)... did I add the 8021 version of the instruction by mistake? To test the assembler, I assembled all the opcodes with a different assembler for 8048...

**Comment by erkkah** [comment]
I found the problem since I test-compiled and verified with a really old assembler and found the difference when I ran disasm and compared outputs. I have never really used 8048s before I jumped into my current odd project, but looking at the manual, it does look like that opcode could have been added by mistake since it clashes with `mov sts, a` (8041) and `movx @r, a` (8048).

I also notice now when I compare manuals that both remaining `outl` opcodes should be non-flagged, they are available on both 8048 and 8041. Sorry about that.

**Comment by erkkah** [comment]
BTW, which other assembler did you use? I could use the same to verify.

**Comment by mikeakohn** [comment]
Looks like I used sbasm ... could be possible that assembler has a bug or I made a mistake somewhere?

**Comment by erkkah** [comment]
I'll check!

**Comment by erkkah** [comment]
Just checked, I can't get the `outl p0, a` through sbasm either, except when I put it in 8021 - mode, so I removed it.
I couldn't find a generator for the 8048 comparison test, so I duplicated the 8041 one and updated the template. Seems to work!

**Comment by mikeakohn** [comment]
Now I wonder why I did gen_8041.py instead of 8048. Anyway.. I just have one thing.. I'm a little picky about consistency. In the 8048.txt text files.. can you make the p1 lowercase so it matches the rest of the file? This really awesome btw :).

**Comment by erkkah** [comment]
Of course. :)

I'm glad that I found your project to base my NS405 - implementation on rather than having to start from scratch!

**Comment by mikeakohn** [comment]
Merged! Thanks!! :)

**Pull request merged**
