### PR TITLE
Add include files for STC 8051 and Silicon Lab C8051Fxx

### PR DESCRIPTION
**Pull request by cjacker**
~~Modern mcs-51 products such as C8051Fx series, STC12/15/8x series provide more I/O ports.~~

~~According to C8051Fx and STC12/15/8x datasheets, these changes:~~

~~1, add P4 to P7 SFR to address map and make them bit addressable, such as "P4.0" can be used.~~
~~2, fix a typo in get_bit_address. 0x3f should be 0x2f~~

3, Add include files for all STC MCU models.

4, Add include files for Silicon Labs' C8051Fxx, these headers converted from SDCC.

5, Add some samples to use these include file.

Edit:
According to recent upstream changes, it is not necessary to change the c codes.

### CODE REVIEW

**Comment by mikeakohn** [comment]
What you did would have conflicted with something I was working on to move all the register defines out of the C file. I believe you should be able to make a new merge request with no C changes at all, if you do need to make C changes please let me know.

The extra includes are pretty cool btw :).

**Comment by cjacker** [comment]
> What you did would have conflicted with something I was working on to move all the register defines out of the C file. I believe you should be able to make a new merge request with no C changes at all, if you do need to make C changes please let me know.
> 
> The extra includes are pretty cool btw :).

> What you did would have conflicted with something I was working on to move all the register defines out of the C file. I believe you should be able to make a new merge request with no C changes at all, if you do need to make C changes please let me know.
> 

It's great that no hardcode SFR in c codes, then we can define all of them in include file.

> The extra includes are pretty cool btw :).

I will re-generate the inc files and submit pull request since SFR defined in c codes had been filtered out.

**Comment by mikeakohn** [comment]
This is awesome.. I think there's just one thing that makes me uncomfortable.. and that's the copyright in the sample programs. You should definitely take credit for your work and put your name on it (like how it is in the include files).. but .. maybe there's a few things. If the samples are there for other people to learn from and copy from, it makes it awkward with a copyright like that. Also, I'm not sure if that conflicts with the licensing of the rest of the program.

**Comment by cjacker** [comment]
> This is awesome.. I think there's just one thing that makes me uncomfortable.. and that's the copyright in the sample programs. You should definitely take credit for your work and put your name on it (like how it is in the include files).. but .. maybe there's a few things. If the samples are there for other people to learn from and copy from, it makes it awkward with a copyright like that. Also, I'm not sure if that conflicts with the licensing of the rest of the program.

OK, I will drop the copyright declaration. acctually it's just copied from other samples:-)

**Comment by mikeakohn** [comment]
Sorry for a slow reply... there's one more thing I noticed.. the c8051 files look like they came from another project with someone else's copyright on them. I'm little bit uncomfortable copying someone else's works into this project like that.

**Comment by cjacker** [comment]
> Sorry for a slow reply... there's one more thing I noticed.. the c8051 files look like they came from another project with someone else's copyright on them. I'm little bit uncomfortable copying someone else's works into this project like that.

CF headers converted  from SDCC and licensed under GPL, but I can understood.

This pull request will be closed.

Thanks.

**Comment by mikeakohn** [comment]
I thought the other include files were made by you though?

**Pull request closed without merging**
