### PR TITLE
Makefile: Add missing naken_prog to install target

### PR DESCRIPTION
**Pull request by uffejakobsen**
This trivial patch adds the missing naken_prog to the install target

### CODE REVIEW

**Comment by mikeakohn** [comment]
Have you used the naken_prog program?  I was originally writing that for programming specific ARM chips... not sure how well that program actually works.

**Comment by uffejakobsen** [comment]
Good question :-D  
No, I haven't used it yet
I just found the "orphaned" binary while I was making the package build description for Arch Linux (see https://aur.archlinux.org/packages/naken_asm-git/)
I just assumed that is was an error that it was missing frmo the install :-)

**Comment by uffejakobsen** [comment]
I assume that this means that we should drop this merge request

**Comment by mikeakohn** [comment]
Arch Linux.. that is so cool.  Thank you for doing this :).  Yeah, I think drop the merge request.  I think the appropriate thing for me to do is not build naken_prog by default until it's in a state where people could get use out of it.  I'll fix it tonight.

If there's anything I can do to make it easier for you to package it let me know...  thanks!!

**Pull request closed without merging**
