### PR TITLE
PDP-8 disassembler

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
This adds a PDP-8 disassembler.

There's an assembler too, but it's not finished.  I can remove that part of the pull request.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Resolves #34.

**Comment by larsbrinkhoff** [comment]
The decoding of the OPR instruction is a bit quirky.  It seems to work ok, but maybe there's room for improvement.

**Comment by mikeakohn** [comment]
I need some time to look into it.

**Comment by mikeakohn** [comment]
This looks really nice.  You kept the coding style consistent.  Can you do me a favor and in the pdp8.c files put your name at the time the same way Joe's name is in the 6502.c files?  I like making sure that people who work on this project get their proper credit.

**Comment by larsbrinkhoff** [comment]
Sure, I'll do that!

What about the assembler part?  I really just wanted the disassembler.  Either take the assembler out, or do you want to finish it yourself?

**Comment by mikeakohn** [comment]
Ah.  I think I read this too early in the  morning and missed the part about it not being finished.  Do you not have time to finish it then?  I was also going to ask if you were going to do a simulator too?

**Comment by larsbrinkhoff** [comment]
I wasn't planning on doing anything more than the disassembler, because that's what I have a need for.  I use it to check the output of my own Forth assembler.  As for simulator, I use the one in SIMH.

**Comment by larsbrinkhoff** [comment]
I added a separate commit to remove the assembler.  I can drop the commit, or squash them all together depending on what you decide.

**Comment by mikeakohn** [comment]
Oh no...  leave the assembler in.  Someone (me, you, someone else) will finish it.  I'll mark it as alpha on the naken_asm webpage.  At least the main parts of the code is there so someone can just fill in the blanks instead of messing with the configure script and common files.

**Comment by larsbrinkhoff** [comment]
Ok, I dropped the removal.

**Pull request merged**
